name: AK

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]
    
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Initialize Database
        run: |
          python -c "from database import init_database; init_database()"

      - name: Clear Database
        run: |
          python -c "from clearDB import clear_database; clear_database()"

      - name: Run requirement tests
        run: |
          python -m pytest R1_test.py R2_test.py R3_test.py R4_test.py R5_test.py R6_test.py R7_test.py -v
